export enum SqlQueries {
  AtcGamesCountBySectionType = 'atc-games-count-by-section-type',
  AtcThrowsHits = 'atc-throws-hits',
  AtcThrowsHitsBySectionTypes = 'atc-throws-hits-by-section-types',
  DeleteFromThrow = 'delete-from-throw',
  GamesCount = 'games-count',
  GameParams = 'game-params',
  GameParticipants = 'game-participants',
  History = 'history',
  LongestHitsStreakBySectionTypes = 'longest-hits-streak-by-section-types',
  Players = 'players',
  TotalPlayingTime = 'total-playing-time',
  Throws = 'throws',
  ThrowsGrouped = 'throws-grouped',
}
